# Build Server
FROM golang:1.22.4-alpine AS builder

COPY . /app
WORKDIR /app
RUN go mod tidy
RUN go build -o gin cmd/gin/main.go

# Deploy gin server
FROM alpine:latest AS ginserver

WORKDIR /
COPY --from=builder /app/gin .
EXPOSE 8000
ENTRYPOINT ["/gin"]
